security:
  jwt:
    signer_Key: "630F20D84D4187F778E537CD0AE9582D0DB5DA98057668461651A928F3E3A039477"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database_forum
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vietyts2003@gmail.com
    password: thlsrtwgtsdnxqrf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true